apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jarvis-electricity-mix-exporter.fullname" . }}
  labels:
    {{- include "jarvis-electricity-mix-exporter.labels" . | nindent 4 }}
data:
  entsoe-area: {{ .Values.config.entsoeArea | quote }}
  bq-enable: {{ .Values.config.bqEnable | quote }}
  bq-init: {{ .Values.config.bqInit | quote }}
  bq-project-id: {{ .Values.config.bqProjectID | quote }}
  bq-dataset: {{ .Values.config.bqDataset | quote }}
  bq-table: {{ .Values.config.bqTable | quote }}