areas:
- area: '10YNL----------L'
  country: 'NL'
  exchanges:
  - area: '10YBE----------2'
    country: 'BE'
  - area: '10Y1001A1001A83F'
    country: 'DE'
  - area: '10YDK-1--------W'
    country: 'DK'
  - area: '10YGB----------A'
    country: 'GB'
  - area: '10YNO-2--------T'
    country: 'NO'
- area: '10YBE----------2'
  country: 'BE'
- area: '10Y1001A1001A83F'
  country: 'DE'
- area: '10YDK-1--------W'
  country: 'DK'
- area: '10YGB----------A'
  country: 'GB'
- area: '10YNO-2--------T'
  country: 'NO'